services:
  postgresql:
    container_name: spotify_postgresql
    image: postgres:14.10
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify_password


volumes:
  postgres_data:
